### PR TITLE
Handle unsupported characters

### PR DESCRIPTION
**Pull request by Keisir**
Hi,
this pull request implements the #8 issue. 
This pull request contains changes that allow to save files that contain characters in the name that are not recognized as "valid" on the respective operating system. To make sure that everything works correctly I wrote a simple migration for it. This only causes that during this update all notes will be recreated once.

I have already tested the changes on Windows (10) and Ubuntu (22.04 LTS). I could not find any problems.
Unfortunately I can't test the changes on MacOS, because I don't own a device with MacOS.

Tested on:
- [x] Windows (10)
- [x] Ubuntu (22.04 LTS)
- [ ] MacOS

### CODE REVIEW

**Comment by ryanpcmcquen** [comment]
Looks clean. How does this affect imports?

**Comment by Keisir** [comment]
Hey,
glad you brought this up again. I completely missed that creating notes in notebooks that contained unsupported characters didn't work. I have fixed that so far. Other than that, importing is only affected if non-imported changes exist during the update process, as these are then lost.

**Comment by ryanpcmcquen** [comment]
With these changes, couldn't a note with unsupported characters, then be imported with its new name when running 'Import Plain Text'?

I think it is fine if that happens but the README should have a note/warning about it.

**Comment by Keisir** [comment]
Actually, this should not be able to happen. I specially added this simple "migration", which should ensure that all previously created files are deleted once and then recreated with the new name.

But I can add this in the readme to inform about this possibility.

**Comment by ryanpcmcquen** [comment]
> Actually, this should not be able to happen. I specially added this simple "migration", which should ensure that all previously created files are deleted once and then recreated with the new name.
> 
> But I can add this in the readme to inform about this possibility.

But the migration only affects backed up files, not the ones inside of Inkdrop, correct?

Here's the scenario I am imagining:

- User on Windows makes a note called: `Foo:`
- Plugin backs this up as `Foo`.
- User runs 'Import Plain Text'.
- Note gets created as `Foo` inside of Inkdrop, now `Foo:` and `Foo` exist.

**Comment by Keisir** [comment]
> But the migration only affects backed up files, not the ones inside of Inkdrop, correct?

Yes correct, the notes within Inkdrop are not changed.

The last step is performed differently. During the import process the notes are matched with the tree and then with the notes from the .json file. Therefore, a renamed file can also be mapped to the note during import into Inkdrop without any problems.

The json file looks something like this in a shortened form. So as soon as a file from the Tree Array, can be mapped to an entry above from the Notes Property, it will not be considered further in the import.

```json
{
    "version": "0.7.1",
    "books": {
        "book:iGA9f9hcq": "Default"
    },
    "notes": {
        "note:lVga9qPoS": {
            "title": "Foo:",
            "path": "Blatet/Foo.md"
        }
    },
    "tree": [
        "C:\\Users\\test\\Desktop\\inkdrop-backup/PLAIN_TEXT/Blatet/Foo.md"
    ]
}
```

**Comment by Lukassrs** [comment]
> But the migration only affects backed up files, not the ones inside of Inkdrop, correct?

Yes correct, the notes within Inkdrop are not changed.

**Comment by ryanpcmcquen** [comment]
Were you ever able to test this on Mac?

**Comment by Keisir** [comment]
> Unfortunately I can't test the changes on MacOS, because I don't own a device with MacOS.

Unfortunately not, as I don't have a device with macos available.

**Comment by ryanpcmcquen** [comment]
Thank you for this @Keisir I will try to get a release out with it soon.

**Pull request merged**
